export const FETCH_PEOPLE = "FETCH_PEOPLE";
export const RECEIVE_PEOPLE = "RECEIVE_PEOPLE";
export const SELECT_PERSON = "SELECT_PERSON";

export const CAR_LOCATION_REQUEST = "CAR_LOCATION_REQUEST";
export const CAR_LOCATION_SUCCESS = "CAR_LOCATION_SUCCESS";
export const CAR_LOCATION_FAIL = "CAR_LOCATION_FAIL";

export const CAR_MAKE_REQUEST = "CAR_MAKE_REQUEST";
export const CAR_MAKE_SUCCESS = "CAR_MAKE_SUCCESS";
export const CAR_MAKE_FAIL = "CAR_MAKE_FAIL";

export const CAR_MODEL_REQUEST = "CAR_MODEL_REQUEST";
export const CAR_MODEL_SUCCESS = "CAR_MODEL_SUCCESS";
export const CAR_MODEL_FAIL = "CAR_MODEL_FAIL";

export const CAR_QUOTE_REQUEST = "CAR_QUOTE_REQUEST";
export const CAR_QUOTE_SUCCESS = "CAR_QUOTE_SUCCESS";
export const CAR_QUOTE_FAIL = "CAR_QUOTE_FAIL";

export const PICKUP_LOCATION_REQUEST = "PICKUP_LOCATION_REQUEST";
export const PICKUP_LOCATION_SUCCESS = "PICKUP_LOCATION_SUCCESS";
export const PICKUP_LOCATION_FAIL = "PICKUP_LOCATION_FAIL";
export const DROPOFF_LOCATION_REQUEST = "DROPOFF_LOCATION_REQUEST";
export const DROPOFF_LOCATION_SUCCESS = "DROPOFF_LOCATION_SUCCESS";
export const DROPOFF_LOCATION_FAIL = "DROPOFF_LOCATION_FAIL";

export const QUOTE_DETAILS_REQUEST = "QUOTE_DETAILS_REQUEST";
export const QUOTE_DETAILS_SUCCESS = "QUOTE_DETAILS_SUCCESS";
export const QUOTE_DETAILS_FAIL = "QUOTE_DETAILS_FAIL";

export const ADDRESS_SAVE_REQUEST = "ADDRESS_SAVE_REQUEST";
export const ADDRESS_SAVE_SUCCESS = "ADDRESS_SAVE_SUCCESS";
export const ADDRESS_SAVE_FAIL = "ADDRESS_SAVE_FAIL";

export const CUSTOMER_SAVE_REQUEST = "CUSTOMER_SAVE_REQUEST";
export const CUSTOMER_SAVE_SUCCESS = "CUSTOMER_SAVE_SUCCESS";
export const CUSTOMER_SAVE_FAIL = "CUSTOMER_SAVE_FAIL";

export const VEHICLEINFOR_SAVE_REQUEST = "VEHICLEINFOR_SAVE_REQUEST";
export const VEHICLEINFOR_SAVE_SUCCESS = "VEHICLEINFOR_SAVE_SUCCESS";
export const VEHICLEINFOR_SAVE_FAIL = "VEHICLEINFOR_SAVE_FAIL";
